---
- name: Install Python3
  become: yes
  apt:
      name: "{{item}}"
      state: latest
      update_cache: true
  loop:
  - "python3"
  when: (false == python_python3_install) and (ansible_distribution == "Ubuntu")

- name: Install Python Packages
  become: yes
  pip:
      name: "{{item}}"
      state: latest
  loop:
  - "pip"
  - "setuptools"
  - "virtualenv"

- name: Download Pycharm Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/python/pycharm-professional-{{python_pycharm_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/pycharm-{{python_pycharm_version}}.tar.gz"
      mode: 0444
  when: python_pycharm_install

- name: Uncompress Pycharm Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/pycharm-{{python_pycharm_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_software_directory}}/pycharm-{{python_pycharm_version}}/build.txt"
  when: python_pycharm_install

- name: Create Softlink To Pycharm
  become: no
  file:
      src: "{{ansible_user_dir}}/{{base_software_directory}}/pycharm-{{python_pycharm_version}}"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/pycharm"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: python_pycharm_install

- name: Create Desktop Icon For Pycharm
  become: no
  template:
      src: "templates/pycharm.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/pycharm.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0755
  when: python_pycharm_install

- name: Set Global Environment To Have PyCharm Use Shared JDK
  become: yes
  template:
      src: "templates/pycharm-environment.sh.j2"
      dest: "/etc/profile.d/pycharm-environment.sh"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
  when: python_pycharm_share_jdk

- name: Remove PyCharm's Embedded JDK
  become: no
  file:
      path: "{{ansible_user_dir}}/{{base_software_directory}}/pycharm/jre64"
      state: absent
  when: python_pycharm_share_jdk

- name: Download Pycharm Edu Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/python/pycharm-edu-{{python_pycharm_edu_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/pycharm-edu-{{python_pycharm_edu_version}}.tar.gz"
      mode: 0444
  when: python_pycharm_edu_install

- name: Uncompress Pycharm Edu Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/pycharm-edu-{{python_pycharm_edu_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_software_directory}}/pycharm-edu-{{python_pycharm_edu_version}}/build.txt"
  when: python_pycharm_edu_install

- name: Create Softlink To Pycharm Edu
  become: no
  file:
      src: "{{ansible_user_dir}}/{{base_software_directory}}/pycharm-edu-{{python_pycharm_edu_version}}"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/pycharm-edu"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: python_pycharm_edu_install

- name: Create Desktop Icon For Pycharm Edu
  become: no
  template:
      src: "templates/pycharm-edu.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/pycharm-edu.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0755
  when: python_pycharm_edu_install

- name: Remove PyCharm Edu's Embedded JDK
  become: no
  file:
      path: "{{ansible_user_dir}}/{{base_software_directory}}/pycharm-edu/jre"
      state: absent
  when: python_pycharm_share_jdk

- name: Add Python3 Repository
  become: yes
  apt_repository:
      repo: 'ppa:deadsnakes/ppa'
      update_cache: yes
      state: present
  when: python_python3_install and (ansible_distribution == "Ubuntu")

- name: Install Python3 Package
  become: yes
  package:
      name: "{{item}}"
      state: present
      allow_unauthenticated: yes
  loop:
  - "{{operations_python3_version}}"
  when: python_python3_install and (ansible_distribution == "Ubuntu")
